apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      color: blue
  template:
    metadata:
      labels:
        app: messaging-app
        color: blue
    spec:
      containers:
        - name: messaging-app
          image: YOUR_DOCKER_IMAGE
          ports:
            - containerPort: 8000
