apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-green
  labels:
    app: messaging-app
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
      color: green
  template:
    metadata:
      labels:
        app: messaging-app
        color: green
    spec:
      containers:
        - name: messaging-app
          image: YOUR_DOCKER_IMAGE   # use new image tag when ready, e.g. :2.0
          ports:
            - containerPort: 8000
